apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-5s4j
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0036-tenant/tkrw-pr712-0075-0036-app/devfile-sample-5s4j@sha256:1659082d783f1513b1616aac25886e47038b4e41b2394a459c78d97de82b9e5a
        name: my-nodejs
        resources: {}
status: {}
